name: Check watches

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install libraries
        run: |
          pip install firebase-admin requests

      - name: Run checker
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          python main.py
